image_width: 320
image_height: 180

left:
  camera_matrix:
    - 350.0
    - 0.0
    - 160.0
    - 0.0
    - 350.0
    - 90.0
    - 0.0
    - 0.0
    - 1.0
  dist_coeffs:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

right:
  camera_matrix:
    - 350.0
    - 0.0
    - 160.0
    - 0.0
    - 350.0
    - 90.0
    - 0.0
    - 0.0
    - 1.0
  dist_coeffs:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

stereo:
  R:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  T:
    - -0.06
    - 0.0
    - 0.0
  R1:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  R2:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  P1:
    - 350.0
    - 0.0
    - 160.0
    - 0.0
    - 0.0
    - 350.0
    - 90.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
  P2:
    - 350.0
    - 0.0
    - 160.0
    - -21.0
    - 0.0
    - 350.0
    - 90.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
  Q:
    - 1.0
    - 0.0
    - 0.0
    - -160.0
    - 0.0
    - 1.0
    - 0.0
    - -90.0
    - 0.0
    - 0.0
    - 0.0
    - 350.0
    - 0.0
    - 0.0
    - 16.6666667
    - 0.0
